---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: comt-1
          image: karrashanmukh/mytetrisgame:v1
          ports:
          - containerPort: 3000
